PROMPTS = {
    "countryLandBordersCountry": (
        "List every single country that shares a land border with {subject}. "
        "Be exhaustive — do not stop early. Check all directions: north, south, east, west. "
        "Only land borders count, not maritime. Island countries with no land borders return []. "
        "Examples:\n"
        "- Sierra Leone: [\"Guinea\", \"Liberia\"]\n"
        "- New Zealand: []\n"
        "- Germany: [\"Austria\", \"Belgium\", \"Czech Republic\", \"Denmark\", \"France\", \"Luxembourg\", \"Netherlands\", \"Poland\", \"Switzerland\"]\n"
        "Return only a JSON array of country names. No explanation."
    ),
    "hasCapacity": (
        "What is the maximum spectator capacity of {subject}? "
        "Step 1: Identify what type of venue this is (national stadium, club ground, university stadium, indoor arena, community ground, etc.) and what you know about its history or size. "
        "Step 2: Based on what you know, state your best capacity estimate. "
        "Step 3: Return a JSON array with a single integer as a string, no commas, no units. "
        "Round numbers are fine — [\"60000\"] counts as correct if within 5% of the real answer. "
        "Examples:\n"
        "- Al Thumama Stadium in Doha: [\"40000\"] (Qatar 2022 World Cup stadium)\n"
        "- Spartan Stadium in Michigan: [\"75000\"] (large US university stadium)\n"
        "- Concordia Stadium in Montreal: [\"4000\"] (small university ground)\n"
        "Always give your best numeric estimate from the venue type and location — never return an empty answer. "
        "Return only the JSON array on the last line."
    ),
    "hasArea": (
        "What is the total area of {subject} in square kilometers? "
        "For countries use total area (land + inland water). "
        "Return a JSON array with a single number as a string, no units. "
        "Examples:\n"
        "- Israel: [\"20770\"]\n"
        "- Mangareva: [\"15.4\"]\n"
        "- Wellington Island: [\"5556\"]\n"
        "Always give your best numeric estimate — never return an empty answer. No explanation."
    ),
    "personHasCityOfDeath": (
        "In which city did {subject} die? "
        "Step 1: State whether this person is living or deceased, and what you know about them. "
        "Step 2: If deceased, name the city where they died. City only, not country or region. "
        "Step 3: Return your final answer as a JSON array with just the city name. "
        "Examples:\n"
        "- Egbert Mulder: [\"Groningen\"]\n"
        "- Frédéric Chopin: [\"Paris\"]\n"
        "- Dave Keon: []\n"
        "Return [] if the person is still living, or if you are not reasonably confident about the specific city. "
        "Return only the final JSON array on the last line. No other text after it."
    ),
    "awardWonBy": (
        "List every person or organisation that has received the {subject}.\n"
        "This may be an annual prize, a fellowship, an honorary degree, or a diplomatic honour — "
        "the approach is the same: recall as many recipients as you possibly can.\n"
        "\n"
        "How to recall systematically:\n"
        "- Annual prizes: go year by year from the founding year to the present.\n"
        "- Fellowships / memberships (e.g. a national academy): enumerate by cohort, field, or decade.\n"
        "- Honorary degrees: list every honoree you can recall from any era.\n"
        "- Diplomatic / state honours: list every recipient you know regardless of country or era.\n"
        "\n"
        "Rules:\n"
        "- Include ONLY the recipient's name — no years, no winning works, no categories.\n"
        "- Aim for 50 or more names. The longer the list the better — a partial list of 100 names "
        "scores far higher than a tidy list of 10.\n"
        "- If you know only a few recipients, still list them — any answer beats an empty one.\n"
        "- Only return [] if you are certain you know no recipients whatsoever.\n"
        "\n"
        "Examples:\n"
        "- Ballon d'Or: [\"Lionel Messi\", \"Cristiano Ronaldo\", \"Ronaldo\", \"Zinedine Zidane\", "
        "\"Ronaldinho\", \"Kaká\", \"Johan Cruyff\", \"Michel Platini\", \"Marco van Basten\", "
        "\"George Best\", \"Lev Yashin\", \"Franz Beckenbauer\", \"Kevin Keegan\", \"Karl-Heinz Rummenigge\", "
        "\"Luka Modrić\", \"Virgil van Dijk\", \"Erling Haaland\"]\n"
        "- Nobel Peace Prize: [\"Martin Luther King Jr.\", \"Desmond Tutu\", \"Nelson Mandela\", "
        "\"Aung San Suu Kyi\", \"Malala Yousafzai\", \"Elie Wiesel\", \"Mother Teresa\", \"Jimmy Carter\", "
        "\"Barack Obama\", \"Wangari Maathai\", \"Médecins Sans Frontières\", \"ICRC\", \"Henry Kissinger\", "
        "\"Rigoberta Menchú\", \"Dag Hammarskjöld\", \"Albert Schweitzer\"]\n"
        "\n"
        "Return a JSON array of names. No explanation."
    ),
    "companyTradesAtStockExchange": (
        "At which stock exchange does {subject} trade? "
        "A company can be listed on multiple exchanges. "
        "Examples:\n"
        "- Farfetch: [\"New York Stock Exchange\"]\n"
        "- West Japan Railway Company: [\"Tokyo Stock Exchange\", \"Nagoya Stock Exchange\", \"Fukuoka Stock Exchange\"]\n"
        "- Bangladesh Cement Manufacturers Association: []\n"
        "If not publicly traded or unknown, return []. "
        "Return only a JSON array of exchange names. No explanation."
    ),
}


# Alternate prompt styles for the numeric relations, selected via --prompt-style.
# "decompose" asks the model to recall related facts (dimensions, venue tier) and
# derive the number, instead of recalling it directly. Anchor-free: NO concrete
# reference numbers embedded (those caused example-contamination previously).
PROMPT_VARIANTS = {
    "hasArea": {
        "decompose": (
            "I want the total area of {subject} in square kilometers.\n"
            "First recall what {subject} is (island, lake, country, region), where it is, "
            "and its physical extent — its approximate length and width, or how it compares "
            "in size to features you know well.\n"
            "Then use that to work out its area in square kilometers. "
            "For countries use total area (land + inland water).\n"
            "Always give your best numeric estimate — never return an empty answer. "
            "End with a JSON array holding a single number as a string, no units, on the last line."
        ),
        "entity_aware": (
            "What is the total area of {subject} in square kilometers?\n\n"
            "First, identify what kind of entity {subject} is and use the matching rule:\n"
            "  - Country or overseas territory → land area + inland water combined\n"
            "  - Island or island group → total land surface area of all islands\n"
            "  - Lake, reservoir, or inland sea → surface area of the water body itself\n"
            "  - Province, state, county, or district → total area of that administrative unit\n"
            "  - Other geographic feature → total geographic extent in km²\n\n"
            "Then recall what you know about {subject}: where it is and how it compares in size "
            "to similar entities you know well.\n\n"
            "Always give your best numeric estimate — never return [].\n"
            "End with a JSON array holding a single number as a string on the last line.\n"
            "Examples: [\"543965\"] for France, [\"82103\"] for Lake Superior, [\"15.4\"] for Mangareva."
        ),
        "native_lang": (
            "What is the total area of {subject} in square kilometers?\n"
            "Step 1: Identify which country or region {subject} belongs to and its primary local language.\n"
            "Step 2: Recall what you know about {subject} USING THAT LANGUAGE — local-language sources "
            "often have more precise area figures for lesser-known places than English does.\n"
            "Step 3: Give the total area in km² (for countries: land + inland water).\n"
            "Always give your best numeric estimate — never return an empty answer.\n"
            "Return a JSON array with a single number as a string on the last line. No units."
        ),
        "native_lang_anchored": (
            "What is the total area of {subject} in square kilometers?\n"
            "Step 1: Identify what {subject} is — its type (island, lake, country, province, etc.) "
            "and location. If it is an island or sub-national territory, confirm it refers to that "
            "specific geographic feature ONLY, not any larger administrative region or country it belongs to.\n"
            "Step 2: Identify the primary local language of where {subject} is located.\n"
            "Step 3: Recall what local-language sources say about this specific entity's area — "
            "they often have more precise figures for lesser-known places than English sources.\n"
            "Step 4: Apply the correct rule: countries → land + inland water; "
            "islands → the island's land area only; lakes → water surface area.\n"
            "Always give your best numeric estimate — never return [].\n"
            "Return a JSON array with a single number as a string on the last line. No units."
        ),
    },
    "hasCapacity": {
        "native_lang": (
            "What is the maximum spectator capacity of {subject}?\n"
            "Step 1: Identify which country and city {subject} is in, and the local language there.\n"
            "Step 2: Recall what you know about this venue USING THAT LANGUAGE — local-language sources "
            "usually have more detail on lesser-known venues than English does.\n"
            "Step 3: Give your best specific capacity number.\n"
            "Always give your best estimate — never return [].\n"
            "Return a JSON array with a single integer as a string on the last line."
        ),
        "native_lang_anchored": (
            "What is the maximum spectator capacity of {subject}?\n"
            "Step 1: Identify exactly what {subject} is — the specific venue type (stadium, arena, "
            "indoor hall), the city and country it is in, and what sports or events it hosts. "
            "This anchors us to the correct venue and not a similarly-named one elsewhere.\n"
            "Step 2: Identify the primary local language of the city/country where {subject} is located.\n"
            "Step 3: Recall what local-language sports media or official sources say about this specific "
            "venue's maximum capacity — local sources often have more accurate figures for lesser-known venues.\n"
            "Step 4: Give your best specific capacity number.\n"
            "Always give your best estimate — never return [].\n"
            "Return a JSON array with a single integer as a string on the last line."
        ),
        "decompose": (
            "I want the maximum spectator capacity of {subject}.\n"
            "First recall what {subject} is: the kind of venue, its tier (national stadium, "
            "top-division club ground, lower-division or community ground, university/school "
            "field, indoor arena), the city/country, and any events it has hosted.\n"
            "Venues of the same tier and era have similar capacities — use that to estimate.\n"
            "Always give your best numeric estimate — never return an empty answer. "
            "End with a JSON array holding a single integer as a string, no commas or units, on the last line."
        ),
        "tier_range": (
            "What is the maximum spectator capacity of {subject}?\n\n"
            "Step 1: What is {subject}? Identify the venue type, level of competition, city and country.\n"
            "Step 2: Classify the tier and use the matching capacity range:\n"
            "  - National/international stadium (Olympics, World Cup, major national finals): 50,000–100,000+\n"
            "  - Top professional club ground (top league of a major football country): 20,000–60,000\n"
            "  - Large university or mid-level professional stadium: 10,000–30,000\n"
            "  - Lower-division, minor league, or regional ground: 2,000–12,000\n"
            "  - Indoor arena or velodrome: 5,000–20,000\n"
            "Step 3: Pick a specific number within the appropriate range.\n"
            "Always give your best estimate — never return [].\n"
            "Return a JSON array with a single integer as a string on the last line."
        ),
        "event_recall": (
            "What is the maximum spectator capacity of {subject}?\n\n"
            "Think about the biggest event ever held at {subject} — the most important match, "
            "game, concert, or ceremony hosted there. How many people attended that event?\n"
            "If you don't know the exact event, think about what type of events this venue "
            "regularly hosts and the typical crowd size.\n"
            "That maximum attendance figure gives you the capacity.\n\n"
            "Always give your best estimate — never return [].\n"
            "Return a JSON array with a single integer as a string on the last line."
        ),
        "comparison": (
            "What is the maximum spectator capacity of {subject}?\n\n"
            "Step 1: Name 2-3 venues of the same type (same sport, country, or competition level) "
            "that you know the capacity of.\n"
            "Step 2: Is {subject} bigger, smaller, or similar in size to those venues?\n"
            "Step 3: Estimate the capacity of {subject} based on this comparison.\n\n"
            "Always give your best estimate — never return [].\n"
            "Return a JSON array with a single integer as a string on the last line."
        ),
        "country_tier": (
            "What is the maximum spectator capacity of {subject}?\n\n"
            "Step 1: What country and city is {subject} in, and what type and level of venue is it?\n"
            "Step 2: Estimate capacity using regional norms for that venue type:\n"
            "  - South America (Brazil, Argentina, Colombia): often large, 30,000–100,000\n"
            "  - Western Europe top division: 20,000–80,000; lower divisions: 5,000–20,000\n"
            "  - North America (NFL/MLB/NBA): 17,000–82,500 depending on sport\n"
            "  - East Asia (Japan, South Korea, China): 15,000–70,000\n"
            "  - Africa, South/Southeast Asia, smaller nations: 5,000–40,000\n"
            "Step 3: Give your best specific number within that range.\n"
            "Always give your best estimate — never return [].\n"
            "Return a JSON array with a single integer as a string on the last line."
        ),
        "compare_region": (
            "What is the maximum spectator capacity of {subject}?\n\n"
            "Step 1: Name 2-3 venues of the same type (same sport, country, and competition level) "
            "that you know the capacity of.\n"
            "Step 2: Is {subject} bigger, smaller, or similar in size to those venues? "
            "Use the country and city context to calibrate — regional norms vary "
            "(South American club grounds tend to be larger; lower-division European grounds smaller).\n"
            "Step 3: Give your best capacity estimate based on the comparison and regional context.\n\n"
            "Always give your best estimate — never return [].\n"
            "Return a JSON array with a single integer as a string on the last line."
        ),
        "country_tier_focus": (
            "What is the maximum spectator capacity of {subject}?\n\n"
            "IMPORTANT: Estimate the capacity of THIS specific venue, in the exact city and country "
            "named. Do NOT reuse the capacity of a bigger, more famous venue that has a similar name "
            "or is in the same city — those are different buildings.\n\n"
            "Step 1: What country and city is {subject} in, and what type and level of venue is it? "
            "Is it a top-flight, mid-level, or minor/community venue?\n"
            "Step 2: Estimate capacity using regional norms for that venue type and tier:\n"
            "  - South America (Brazil, Argentina, Colombia): often large, 30,000–100,000\n"
            "  - Western Europe top division: 20,000–80,000; lower divisions: 5,000–20,000\n"
            "  - North America (NFL/MLB/NBA): 17,000–82,500 depending on sport; college/minor smaller\n"
            "  - East Asia (Japan, South Korea, China): 15,000–70,000\n"
            "  - Africa, South/Southeast Asia, smaller nations: 5,000–40,000\n"
            "Step 3: Give your best specific number for THIS venue within that range.\n"
            "Always give your best estimate — never return [].\n"
            "Return a JSON array with a single integer as a string on the last line."
        ),
    },
    "companyTradesAtStockExchange": {
        "regional_recall": (
            "At which stock exchange does {subject} trade?\n"
            "A company can be listed on multiple exchanges.\n\n"
            "Consider all global exchanges, including regional ones:\n"
            "  - Americas: NYSE, NASDAQ, TSX (Canada), B3 (Brazil), BMV (Mexico)\n"
            "  - Europe: London SE, Euronext, Deutsche Börse, SIX Swiss, Warsaw SE, Prague SE\n"
            "  - Middle East & Africa: Tadawul (Saudi), Tel Aviv SE, JSE (South Africa), EGX (Egypt)\n"
            "  - Asia-Pacific: Tokyo SE, Hong Kong SE, Shanghai SE, BSE/NSE (India), Korea SE, "
            "ASX (Australia), Indonesia SE, Bursa Malaysia, SGX (Singapore), Vietnam SE\n"
            "  - Alternative: AIM (London), OTC Markets (US)\n\n"
            "If the company is headquartered in a country with a national exchange, consider "
            "whether it is listed there.\n\n"
            "Examples:\n"
            "- Farfetch: [\"New York Stock Exchange\"]\n"
            "- West Japan Railway Company: [\"Tokyo Stock Exchange\", \"Nagoya Stock Exchange\", \"Fukuoka Stock Exchange\"]\n"
            "- Bangladesh Cement Manufacturers Association: []\n"
            "If not publicly traded or unknown, return []. "
            "Return only a JSON array of exchange names. No explanation."
        ),
        "chain_of_thought": (
            "At which stock exchange does {subject} trade?\n\n"
            "Work through this step by step:\n"
            "Step 1: What is {subject}? (industry, country of origin, approximate size or revenue)\n"
            "Step 2: Is this company publicly traded? "
            "Large or well-known companies are often listed; subsidiaries of private parents and "
            "cooperatives typically are not.\n"
            "Step 3: If publicly traded, name the exchange(s) — primary listing and any cross-listings.\n\n"
            "Examples:\n"
            "- Farfetch: [\"New York Stock Exchange\"]\n"
            "- West Japan Railway Company: [\"Tokyo Stock Exchange\", \"Nagoya Stock Exchange\", \"Fukuoka Stock Exchange\"]\n"
            "- Bangladesh Cement Manufacturers Association: []\n"
            "Return only a JSON array of exchange names on the last line. If not listed, return []."
        ),
        "listed_check": (
            "Does {subject} have its own shares that trade on a stock exchange, and if so where?\n\n"
            "Step 1 — Eligibility. Decide whether {subject} ITSELF has publicly traded shares "
            "under its own name RIGHT NOW. Answer 'no' (→ []) if any of these apply:\n"
            "  - It is a subsidiary whose shares are not separately listed (only its parent trades). "
            "e.g. a brand or unit owned by a larger listed group.\n"
            "  - It is privately held (family/founder/private-equity owned, no public shares).\n"
            "  - It is a cooperative, mutual, association, government body, or non-profit.\n"
            "  - It was taken private, acquired, or delisted and no longer trades on its own.\n"
            "Only answer 'yes' if the company files as an independent public issuer under its own name.\n"
            "Step 2 — Exchange. If and only if eligible, name the exchange(s) it is listed on "
            "(primary listing plus any cross-listings).\n\n"
            "Be strict: if you are not confident the company is independently listed, return [].\n"
            "Examples:\n"
            "- Farfetch (independent public company): [\"New York Stock Exchange\"]\n"
            "- West Japan Railway Company: [\"Tokyo Stock Exchange\", \"Nagoya Stock Exchange\", \"Fukuoka Stock Exchange\"]\n"
            "- Kintetsu Real Estate (subsidiary of listed Kintetsu Group): []\n"
            "- Bangladesh Cement Manufacturers Association (industry body): []\n"
            "Return only a JSON array of exchange names on the last line. If not independently listed, return []."
        ),
        # --- meta-prompting candidates (Phase 26): model-refined, precision-focused ---
        "meta_precision": (
            "Return a JSON array of stock exchanges where {subject} is listed.\n"
            "Strictly enforce precision: only include an exchange for which you have definitive "
            "knowledge of an actual listing. Do not infer a listing from the company's name, "
            "headquarters, or sector. Do not include private companies, or subsidiaries/acquired "
            "companies whose shares are not separately traded. If the company is not publicly "
            "traded or the listing is unknown, return [].\n"
            "Examples:\n"
            "- Farfetch: [\"New York Stock Exchange\"]\n"
            "- West Japan Railway Company: [\"Tokyo Stock Exchange\", \"Nagoya Stock Exchange\", \"Fukuoka Stock Exchange\"]\n"
            "- Bangladesh Cement Manufacturers Association: []\n"
            "Return only a JSON array of exchange names. No explanation."
        ),
        "meta_verify": (
            "Identify the stock exchange(s) for {subject}.\n"
            "Before outputting, verify two things: (1) the company is publicly traded (not private "
            "or an unlisted subsidiary), and (2) the exchange is a listing you actually recall — "
            "not a guess based on the company's name or region. If either check fails, return [].\n"
            "Examples:\n"
            "- Farfetch: [\"New York Stock Exchange\"]\n"
            "- West Japan Railway Company: [\"Tokyo Stock Exchange\", \"Nagoya Stock Exchange\", \"Fukuoka Stock Exchange\"]\n"
            "- Bangladesh Cement Manufacturers Association: []\n"
            "Return only a JSON array of exchange names on the last line."
        ),
        "anti_confusion": (
            "At which stock exchange does {subject} trade?\n\n"
            "Two common mistakes to avoid:\n"
            "1. NYSE vs Nasdaq confusion. These are DIFFERENT exchanges. Use the ticker symbol "
            "to identify which one — NYSE tickers are usually 1–3 letters (e.g. DLB, EIX, IBM, AXP); "
            "Nasdaq tickers are usually 4+ letters (e.g. MSFT, AAPL, CSCO, AMZN). "
            "Do NOT guess — if you are unsure which US exchange, return [].\n"
            "2. Wrong-country default. A company may be listed in a country DIFFERENT from its "
            "headquarters. Do not return an exchange solely because the company is based there. "
            "Only name an exchange you actually recall the company trading on.\n\n"
            "Rules:\n"
            "- Only include exchanges where the company has its OWN shares listed independently "
            "(not a subsidiary or private company).\n"
            "- Return [] if not publicly traded, or if you are not confident of the exchange.\n\n"
            "Examples:\n"
            "- Farfetch: [\"New York Stock Exchange\"]\n"
            "- West Japan Railway Company: [\"Tokyo Stock Exchange\", \"Nagoya Stock Exchange\", \"Fukuoka Stock Exchange\"]\n"
            "- Bangladesh Cement Manufacturers Association: []\n"
            "Return only a JSON array of exchange names. No explanation."
        ),
    },
    "awardWonBy": {
        "year_sweep": (
            "List every recipient of the {subject}, going year by year from when it was first awarded "
            "through 2026.\n"
            "\n"
            "Format each year you are confident about as: YEAR: Name\n"
            "Skip years you are genuinely uncertain about — do not guess a name just to fill a gap.\n"
            "For fellowships or memberships elected by cohort, go decade by decade instead.\n"
            "\n"
            "Rules:\n"
            "- Confirmed recipients only — not nominees, shortlisted candidates, or people merely "
            "associated with the award.\n"
            "- Names only — no categories, no winning works, no extra commentary.\n"
            "- Annual prizes with one winner: one name per year. Multiple-winner prizes: list all you know.\n"
            "\n"
            "After the year-by-year section, compile every name into a single JSON array on the last line.\n"
            "Return only the JSON array if you cannot recall any specific year–recipient pairs.\n"
            "\n"
            "Example (Turing Award excerpt):\n"
            "1966: Alan Perlis\n"
            "1967: Maurice Wilkes\n"
            "1968: Richard Hamming\n"
            "[\"Alan Perlis\", \"Maurice Wilkes\", \"Richard Hamming\", ...]"
        ),
        "alphabetical": (
            "List every person or organisation that has received the {subject}.\n"
            "\n"
            "Recall by NAME, not by year. Going year-by-year makes you loop and second-guess a "
            "single year forever. Instead, sweep your memory by first letter: think of recipients "
            "whose surname starts with A, then B, then C, and so on to Z. Write each name down as "
            "soon as it comes to mind and move on — do not stop to verify the exact year.\n"
            "\n"
            "Rules:\n"
            "- Include ONLY the recipient's name — no years, no winning works, no categories.\n"
            "- Aim for 50 or more names. A partial list of 100 names scores far higher than 10.\n"
            "- Do not deliberate about any single name — if you are fairly sure someone received it, "
            "include them and keep going.\n"
            "- Only return [] if you are certain you know no recipients whatsoever.\n"
            "\n"
            "Write the full JSON array of names as your FIRST output, before any reasoning.\n"
            "Examples:\n"
            "- Nobel Peace Prize: [\"Martin Luther King Jr.\", \"Desmond Tutu\", \"Nelson Mandela\", "
            "\"Malala Yousafzai\", \"Elie Wiesel\", \"Mother Teresa\", \"Jimmy Carter\", \"Barack Obama\", "
            "\"Wangari Maathai\", \"Henry Kissinger\", \"Rigoberta Menchú\", \"Albert Schweitzer\"]\n"
            "\n"
            "Return a JSON array of names. No explanation."
        ),
    },
    "personHasCityOfDeath": {
        "recent_aware": (
            "In which city did {subject} die?\n\n"
            "Step 1: Who is {subject}? What are they known for, and when were they most active?\n"
            "Step 2: As of 2026, consider deaths through 2025. "
            "If {subject} was prominent in the 1980s–2010s and was likely in their 70s–90s, "
            "they may have passed away recently — commit to a city if you have reasonable confidence.\n"
            "Step 3: If deceased, name the city. "
            "Return [] only if you are confident the person is still alive, or you have "
            "no information at all about their death.\n\n"
            "City granularity only — not country or region.\n"
            "Examples:\n"
            "- Egbert Mulder: [\"Groningen\"]\n"
            "- Frédéric Chopin: [\"Paris\"]\n"
            "- Dave Keon: []\n"
            "Return only the JSON array on the last line."
        ),
        "timeline": (
            "In which city did {subject} die?\n\n"
            "Do NOT jump to the city {subject} is most famously associated with — that is "
            "usually wrong. Instead reconstruct their life, then reason to the death city:\n"
            "Step 1: Who is {subject}? Roughly when were they born?\n"
            "Step 2: Trace their timeline — where were they born, where did they build their "
            "career, and CRUCIALLY where did they live in their FINAL years? People retire and "
            "relocate; the death city is usually where they lived last, not their birthplace, "
            "their career city, or a national capital.\n"
            "Step 3: Based on where they spent their last years, name the city where they died.\n"
            "Return [] only if you are confident they are still alive, or have no information.\n"
            "City granularity only.\n"
            "Examples:\n"
            "- Egbert Mulder: [\"Groningen\"]\n"
            "- Frédéric Chopin: [\"Paris\"]\n"
            "- Dave Keon: []\n"
            "Return only the JSON array on the last line."
        ),
        "native_lang": (
            "In which city did {subject} die?\n\n"
            "Step 1: Identify {subject}'s nationality and primary language.\n"
            "Step 2: Recall what you know about them USING THAT LANGUAGE — local-language "
            "sources usually have far more detail about lesser-known people, including where "
            "they lived and died, than English sources do. Think through their life in that "
            "language.\n"
            "Step 3: Give the city where they died (city only), written in its common form.\n"
            "Return [] only if you are confident they are still alive, or have no information.\n"
            "Examples:\n"
            "- Egbert Mulder: [\"Groningen\"]\n"
            "- Frédéric Chopin: [\"Paris\"]\n"
            "- Dave Keon: []\n"
            "Return only the JSON array on the last line."
        ),
        "timeline_native": (
            "In which city did {subject} die?\n\n"
            "Step 1: Identify {subject}'s nationality and primary language.\n"
            "Step 2: Using that language (local-language sources have far more detail on "
            "lesser-known people), reconstruct their life: where were they born, where did they "
            "build their career, and CRUCIALLY where did they live in their FINAL years?\n"
            "Step 3: The death city is usually where they lived last — NOT their birthplace, "
            "their career city, or a national capital. Do not default to the city they are most "
            "famous for. Based on their final-years location, name the city where they died.\n"
            "Return [] only if you are confident they are still alive, or have no information.\n"
            "City granularity only.\n"
            "Examples:\n"
            "- Egbert Mulder: [\"Groningen\"]\n"
            "- Frédéric Chopin: [\"Paris\"]\n"
            "- Dave Keon: []\n"
            "Return only the JSON array on the last line."
        ),
        "city_precision": (
            "In which city did {subject} die?\n\n"
            "Step 1: Is this person living or deceased?\n"
            "Step 2: If deceased, which city? Use the specific city name as it appears in obituaries.\n"
            "Precision rules:\n"
            "  - US: Brooklyn, Queens, Manhattan, Bronx, Staten Island → 'New York City'\n"
            "  - US: West Hollywood, Beverly Hills, Santa Monica → 'Los Angeles'\n"
            "  - US: Cambridge MA is 'Cambridge', not 'Boston'\n"
            "  - UK: use the specific town or city, not the nearest major city\n"
            "  - Elsewhere: use the municipality where the death occurred\n"
            "Step 3: Return [] if still living, or if you have no reliable information.\n\n"
            "Examples:\n"
            "- Egbert Mulder: [\"Groningen\"]\n"
            "- Frédéric Chopin: [\"Paris\"]\n"
            "- Dave Keon: []\n"
            "Return only the JSON array on the last line."
        ),
        "recent_precise": (
            "In which city did {subject} die?\n\n"
            "Step 1: Who is {subject}? What are they known for, and when were they most active?\n"
            "Step 2: Consider deaths through 2025. If {subject} was prominent in the 1980s–2010s "
            "and was likely in their 70s–90s, they may have passed away recently — "
            "commit to a city if you have reasonable confidence.\n"
            "Step 3: If deceased, name the city using obituary-standard precision:\n"
            "  - US: Brooklyn, Queens, Manhattan → 'New York City'; "
            "West Hollywood, Beverly Hills, Santa Monica → 'Los Angeles'\n"
            "  - UK: use the specific town (not nearest major city)\n"
            "  - Elsewhere: use the municipality\n"
            "Return [] only if you are confident the person is still alive, "
            "or you have genuinely no information. Do not return [] just because you are uncertain — "
            "a best guess is better than nothing.\n\n"
            "Examples:\n"
            "- Egbert Mulder: [\"Groningen\"]\n"
            "- Frédéric Chopin: [\"Paris\"]\n"
            "- Dave Keon: []\n"
            "Return only the JSON array on the last line."
        ),
        # --- meta-prompting candidates (Phase 26): anti-default + confidence gating ---
        "meta_antidefault": (
            "In which city did {subject} die?\n\n"
            "Step 1: Identify {subject} and their vital status. If alive or status unknown, go to Step 3.\n"
            "Step 2: Recall the exact city of death. Separate confirmed fact from inference: is the "
            "recalled city the ACTUAL place of death, or merely where they were born, worked, or are "
            "culturally associated? Geographic defaults (national capitals, major hubs, career bases) "
            "are not substitutes for the real death location.\n"
            "Step 3: Output the city ONLY if you have a direct, specific memory of where they died. "
            "If you know they died but not where, or you are inferring from association, return [].\n"
            "City granularity only.\n"
            "Examples:\n"
            "- Egbert Mulder: [\"Groningen\"]\n"
            "- Frédéric Chopin: [\"Paris\"]\n"
            "- Dave Keon: []\n"
            "Return only the JSON array on the last line."
        ),
        "committed": (
            "In which city did {subject} die?\n\n"
            "It is 2026. Your knowledge includes events through early 2026, including deaths in "
            "2023, 2024, and 2025.\n\n"
            "Step 1: Who is {subject}? Roughly when were they born and what are they known for?\n"
            "Step 2: Assess vital status using this rule:\n"
            "  - Born before 1940 → assume deceased unless you have clear evidence they are alive.\n"
            "  - Born 1940–1960 → likely deceased if not recently active; lean toward predicting.\n"
            "  - Born after 1960 → reason carefully; return [] only if you believe they are alive.\n"
            "Step 3: If deceased or very likely deceased — name the city where they died. "
            "A confident best guess beats returning [].\n"
            "Step 4: Return [] ONLY if you are confident this person is currently alive, or you "
            "have no information about them whatsoever.\n\n"
            "City granularity only — not country or region.\n"
            "Examples:\n"
            "- Egbert Mulder: [\"Groningen\"]\n"
            "- Frédéric Chopin: [\"Paris\"]\n"
            "- Dave Keon: []\n"
            "Return only the JSON array on the last line."
        ),
        "meta_gating": (
            "Determine the city of death for {subject}.\n\n"
            "Step 1: Is {subject} deceased? If alive or uncertain, skip to Step 3.\n"
            "Step 2: Retrieve the death location, then run an anti-default check: do NOT output a "
            "city if it merely matches their birthplace, primary residence, or national capital "
            "unless you specifically recall it as the death site. If your knowledge is vague or "
            "relies on association, treat it as missing.\n"
            "Step 3: Output a city only if you can recall a specific detail confirming it as the "
            "death place. Otherwise return [].\n"
            "City granularity only.\n"
            "Examples:\n"
            "- Egbert Mulder: [\"Groningen\"]\n"
            "- Frédéric Chopin: [\"Paris\"]\n"
            "- Dave Keon: []\n"
            "Return only the JSON array on the last line."
        ),
    },
}


# Second-pass self-verification, applied on top of any base prompt via --verify.
VERIFY_META = {
    "hasArea": ("total area in square kilometers", "number"),
    "hasCapacity": ("maximum spectator capacity", "integer"),
}

VERIFY_TEMPLATE = (
    "For the {relation_desc} of \"{subject}\", an initial estimate of {answer} was given.\n"
    "Check whether that value is plausible for this specific entity — consider its type, "
    "location, and how it compares to similar entities you know. If the initial estimate is "
    "clearly too high or too low, give a corrected value; otherwise keep it.\n"
    "Respond with a JSON array holding a single {numtype} as a string, no units, on the last line."
)
